# Generated by Django 4.0.3 on 2022-03-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': ('Предмет',),
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('status', models.IntegerField(choices=[(2, 'Не начато'), (1, 'В работе'), (3, 'Сдано')], default=2, verbose_name='Статус')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='works.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
