# Generated by Django 4.0.3 on 2022-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['deadline', 'status', 'name'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.IntegerField(choices=[(2, 'Не начато'), (1, 'В работе'), (3, 'Выполнено')], default=2, verbose_name='Статус'),
        ),
    ]
